project:
  type: website
  output-dir: docs  

website:
  title: "Linux Study Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/snagjincha
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



